# Generated by Django 5.1.2 on 2024-11-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='ab', max_length=255),
        ),
    ]
